backend:
  name: git-gateway
  branch: main

media_folder: "Gorseller"
public_folder: "/Gorseller"

collections:
  - name: "urunler"
    label: "Ürünler"
    files:
      - file: "content/tesbihler.json"
        label: "Ürünler"
        name: "urunler_listesi"
        fields:
          - { label: "Pipolar", name: "pipolar", widget: "list", fields: [
              { label: "Resim", name: "image", widget: "image" },
              { label: "Baslik", name: "title", widget: "string" }
            ] }
          - { label: "Sigaralık", name: "sigaralik", widget: "list", fields: [
              { label: "Resim", name: "image", widget: "image" },
              { label: "Baslik", name: "title", widget: "string" }
            ] }
