backend:
  name: git-gateway
  branch: main

media_folder: "Görseller"
public_folder: "/Görseller"

collections:
  - name: "tesbihler"
    label: "Tesbihler"
    folder: "content/tesbihler"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Resim", name: "image", widget: "image" }
      - { label: "Baslik", name: "title", widget: "string" }


  - name: "takilar"
    label: "Takılar"
    files:
      - file: "content/takilar.json"
        label: "Takılar Listesi"
        name: "takilar_listesi"
        fields:
          - { label: "Urunler", name: "items", widget: "list", fields: [
              { label: "Resim", name: "image", widget: "image" },
              { label: "Baslik", name: "title", widget: "string" }
            ] }
