backend:
  name: git-gateway
  branch: main

media_folder: "Görseller"
public_folder: "/Görseller"

collections:
  - name: "tesbihler"
    label: "Tesbihler"
    file: "content/tesbihler.json"
    fields:
      - { label: "Ürünler", name: "items", widget: "list", fields: [
          { label: "Resim", name: "image", widget: "image" },
          { label: "Başlık", name: "title", widget: "string" }
        ] }

  - name: "takilar"
    label: "Takılar"
    file: "content/takilar.json"
    fields:
      - { label: "Ürünler", name: "items", widget: "list", fields: [
          { label: "Resim", name: "image", widget: "image" },
          { label: "Başlık", name: "title", widget: "string" }
        ] }
