backend:
  name: git-gateway
  branch: main

media_folder: "Görseller"
public_folder: "/Görseller"

collections:
  - name: "tesbihler"
    label: "Tesbihler"
    files:
      - file: "content/tesbihler.json"
        label: "Tesbihler Listesi"
        name: "tesbihler_listesi"
        fields:
          - { label: "Ürünler", name: "items", widget: "list", fields: [
              { label: "Resim", name: "image", widget: "image" },
              { label: "Başlık", name: "title", widget: "string" }
            ] }

  - name: "takilar"
    label: "Takılar"
    files:
      - file: "content/takilar.json"
        label: "Takılar Listesi"
        name: "takilar_listesi"
        fields:
          - { label: "Ürünler", name: "items", widget: "list", fields: [
              { label: "Resim", name: "image", widget: "image" },
              { label: "Başlık", name: "title", widget: "string" }
            ] }
